name: 西水源头
description: 虽变化万端，而理唯一贯
meta_description: 技术与沉思

markdown: redcarpet
highlighter: pygments
logo: logo.jpg
paginate: 15
baseurl: /
domain_name: 'http://westsource.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'westsource.github.io'
author:         '黄超'
